name: Audit, build and push to Docker Hub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPO: reddit-api-clone

jobs:
  audit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: go build -v ./...
      - name: Run go vet
        run: go vet ./...
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run staticcheck
        run: staticcheck ./...
      - name: Install golint
        run: go install golang.org/x/lint/golint@latest
      - name: Run golint
        run: golint ./...
      # - name: Run tests , TODO: modify the pipeline to spin up Docker, before running integration tests
      #   run: go test -race -vet=off ./...
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Build and tag Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: /Users/melvinkimathi/Documents/Other/cloned github repos/Go/Design-the-Reddit-API/Dockerfile
          push: false
          tags: ${{ env.DOCKER_REPO }}:latest
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Push Docker Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REPO }}:latest
  